name: Build LaTeX document
on: 
  push:
    paths-ignore:
      - root.pdf
  schedule:
    - cron: '0 22 * * *'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: paper.pdf
      - name: Commit and push PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f root.pdf
          git commit -m "Add generated PDF" -a
          git push

      
            
